import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class WithdrawForm extends javax.swing.JFrame {
    
    public WithdrawForm() {
        initComponents();
        getContentPane().setBackground(Color.gray);
    }
    
    public void setNameText (String Name){
        Wname.setText(Name);
    }
    
    public void setAcnoText (String accNO){
        Wan.setText(accNO);
    }
    
    public void setCurrentBalanceText (String cBln){
        Wcbalance.setText(cBln);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Wcbalance = new javax.swing.JTextField();
        Wan = new javax.swing.JTextField();
        Wname = new javax.swing.JTextField();
        btWd = new javax.swing.JButton();
        Wbtback = new javax.swing.JButton();
        money = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("WITHDRAW");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Account Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Current Balance :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nominal Withdraw :");

        Wcbalance.setEditable(false);
        Wcbalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Wan.setEditable(false);
        Wan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Wname.setEditable(false);
        Wname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btWd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btWd.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Downloads\\minus.gif")); // NOI18N
        btWd.setText("Withdraw");
        btWd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWdActionPerformed(evt);
            }
        });

        Wbtback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Wbtback.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Downloads\\backk1.png")); // NOI18N
        Wbtback.setText("Back");
        Wbtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbtbackActionPerformed(evt);
            }
        });

        money.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected", "20", "40", "60", "80", "100", "200" }));
        money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Wan, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(Wname, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(Wcbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(money, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Wbtback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btWd)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wcbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btWd)
                    .addComponent(Wbtback))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WbtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbtbackActionPerformed
        // TODO add your handling code here:
        Mainmenu.getMainmenu().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_WbtbackActionPerformed

    private void btWdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWdActionPerformed
        // TODO add your handling code here:
        try {
        Connection con = db.conn();
        String accNum = Wan.getText(); // Ambil nomor akun dari teksfield
        int withdrawalAmount = Integer.parseInt((String) money.getSelectedItem()); // Ambil jumlah penarikan dari combobox

        // Validasi bahwa saldo mencukupi untuk penarikan
        PreparedStatement validateStmt = con.prepareStatement("SELECT current_balance FROM customer WHERE acc_no = ?");
        validateStmt.setString(1, accNum);
        ResultSet rs = validateStmt.executeQuery();
        if (rs.next()) {
            int currentBalance = rs.getInt("current_balance");
            if (currentBalance >= withdrawalAmount) {
                // Lakukan penarikan dan update saldo di database
                int newBalance = currentBalance - withdrawalAmount;
                PreparedStatement updateStmt = con.prepareStatement("UPDATE customer SET current_balance = ? WHERE acc_no = ?");
                updateStmt.setInt(1, newBalance);
                updateStmt.setString(2, accNum);
                updateStmt.executeUpdate();

                JOptionPane.showMessageDialog(rootPane, "Withdraw successful!");
                
                Mainmenu mm = Mainmenu.getMainmenu();
                mm.updateBalance(String.valueOf(newBalance));
                
                // Tampilkan kembali Mainmenu dan dispose WithdrawForm
                mm.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Insufficient balance!");
            }
        }
        con.close();
    } catch (Exception e) {
        // Handle eksepsi
    }
    }//GEN-LAST:event_btWdActionPerformed

    private void moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Wan;
    private javax.swing.JButton Wbtback;
    private javax.swing.JTextField Wcbalance;
    private javax.swing.JTextField Wname;
    private javax.swing.JButton btWd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> money;
    // End of variables declaration//GEN-END:variables
}
